services:
  postgresql:
    container_name: postgresql
    image: postgis/postgis:16-3.4
    expose:
      - '5432'
    env_file: ./backend/.env
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - secunda-network
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - '8000'
    env_file: ./backend/.env
    volumes:
      - ./backend:/application
    restart: unless-stopped
    command: sh -c 'alembic upgrade head && uvicorn main:application --host 0.0.0.0 --port 8000 --reload'
    networks:
      - secunda-network
    depends_on:
      - postgresql
  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    ports:
      - '80:80'
    env_file: ./backend/.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - secunda-network
    depends_on:
      - backend

networks:
  secunda-network:
    driver: bridge
    external: true

volumes:
  data: